language: android
jdk: oraclejdk8
sudo: false

env:
 global:
  - ANDROID_API_LEVEL=21
  - ANDROID_EMULATOR_LEVEL=18
  - ANDROID_BUILD_TOOLS_VERSION=26.1.1
  - ADB_INSTALL_TIMEOUT=20
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - QEMU_AUDIO_DRV=none

  android:
   components:
   - tools
   - platform-tools
   - tools
   - build-tools-$ANDROID_BUILD_TOOLS_VERSION
   - android-$ANDROID_API_LEVEL
   - android-$ANDROID_EMULATOR_LEVEL
   - extra-android-support
   - extra-google-m2repository
   - extra-android-m2repository
   - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

before_install:
- chmod +x gradlew

before_script:
 - android list targets
 - echo no | android create avd --force -n test -t android-ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
 - emulator -avd test -no-window &
 - android-wait-for-emulator

script:
- ./gradlew dependencyCheckAnalyze build
- adb shell input keyevent 82
- ./gradlew connectedCheck -PdisablePreDex --stacktrace
